### ISSUE TITLE
bug - AD dccmonitor checks out of sync with dccvalidator checks 

### ISSUE THREAD

**Issue by avanlinden** [Sage-Bionetworks/dccmonitor#123] opened 2021-10-26 17:46 UTC
In reviewing metadata validation efforts for the MC-CAA study in AD, I noticed that [dccmonitor](https://www.synapse.org/#!Synapse:syn25878248) is not flagging errors that are being caught in [dccvalidator](https://www.synapse.org/#!Synapse:syn25878247). 

We have a contributor who tried validating individual and biospecimen files for an existing study that were missing columns and rows included in the current versions of those files. dccvalidator correctly flagged those errors, but dccmonitor did not for the exact same files(screenshots attached). Need to investigate where dccmonitor is out of sync and fix it. 

<img width="1165" alt="dccmonitor-checks-MCCAA" src="https://user-images.githubusercontent.com/11965371/138932664-db811d4a-4a73-4d3e-9179-8e62889ff512.png">
<img width="1152" alt="dccvalidator-checks-MCCAA" src="https://user-images.githubusercontent.com/11965371/138932667-847650a8-24f1-4332-9fd2-65bf2bea01e3.png">

@kelshmo @danlu1 Have you noticed any issues with the PEC dccmonitor app?

**Comment by danlu1** [comment] 2022-01-13 19:41
@avanlinden I will meet with Anthony to discuss this. Just to get more info on this. Have you tried to run dccmonitor in incognito window? And how it goes?

**Comment by avanlinden** [comment] 2022-01-14 18:01
@danlu1 I did try running dccmonitor in an incognito and it's still missing the errors flagged by dccvalidator.

In the process of trying to reproduce this error, I did some tests with files from several studies and encountered a rat's nest of _other_ bugs in dccvalidator (e.g. metadata files for existing studies being incorrect, errors for missing columns that do not exist in the template, etc). I can't even appropriately isolate this error because there are too many others at the same time. 

I think we need to do some more comprehensive testing with demo files to try and document exactly which checks aren't working and why. :(

**Comment by avanlinden** [comment] 2022-01-14 18:15
Screenshot of the dccvalidator errors for the [APOEPSC study](https://www.synapse.org/#!Synapse:syn25914225), which I was using to test:
<img width="882" alt="APOEPSC-dccvalidator-errors" src="https://user-images.githubusercontent.com/11965371/149564694-b8a29836-f6fe-4c90-a8ef-c7318a49f672.png">

The individual metadata file currently in the study only has two rows; I created a test version where I deleted one of the rows to see if dccvalidator flagged it. It _should_ have told me that one individualID that was previously part of the study was missing; instead it told me that 9 other individualIDs that were previously part of the study were missing. But it should be checking against the current individual file, which honest to goodness only has two individualIDs total. 

I can do a more detailed debug on this next week.

**Comment by afwillia** [comment] 2022-01-20 21:51
@avanlinden It seems that dccvalidator is using the [AMP-AD Specimen table](https://www.synapse.org/#!Synapse:syn21578908/tables/) as the "truth" for all individualIDs, not the previously uploaded individual metadata file. Does that sound right to you?

**Comment by afwillia** [comment] 2022-01-20 22:02
@danlu1  @avanlinden also, I'm getting denied trying to push a branch with some updates. Can you give me access?

**Comment by danlu1** [comment] 2022-01-20 22:24
> @danlu1 @avanlinden also, I'm getting denied trying to push a branch with some updates. Can you give me access?

on it.

**Comment by afwillia** [comment] 2022-01-20 23:50
Thanks!

**Comment by afwillia** [comment] 2022-01-21 00:12
As for the original issue @avanlinden raised with the MC-CAA immunoassay data, I think I figured out why dccmonitor is not flagging the issues dccvalidator did.

1. "Missing columns in the biospecimen metadata file"
dccmonitor differs slightly from dccvalidator in how it finds the template dataset for each biospecimen type in the manifest. In this case, columns with "NaN" were not being turned into true NA's and omitted, causing dccmonitor to skip that particular check. I pushed a preliminary fix for this, but should probably add more testing.

2. "Some individualIDs/specimenIDs missing from the individual/biospecimen metadata"
dccvalidator::check_all() has an argument for the specimen table [AMP-AD specimen table](https://www.synapse.org/#!Synapse:syn21578908/tables/) which is used to identify all of the individualIDs and specimenIDs for a study. dccmonitor does not pass a sample_table to check_all(), so that always gets skipped. I will need to figure out how to add the sample table to dccmonitor to make it consistent with dccvalidator

**Comment by avanlinden** [comment] 2022-01-21 00:18
> @avanlinden It seems that dccvalidator is using the [AMP-AD Specimen table](https://www.synapse.org/#!Synapse:syn21578908/tables/) as the "truth" for all individualIDs, not the previously uploaded individual metadata file. Does that sound right to you?

Oh you're totally right, I forgot about that. There have been issues updating the specimen table (which I thought I had solved, but maybe not). I've been trying to hold everything together with scotch tape and chewing gum since Nicole left so clearly some things are falling through the cracks...

**Comment by avanlinden** [comment] 2022-01-21 00:23
@afwillia the code that generates/updates the Specimen Table is here: https://github.com/Sage-Bionetworks/cleanAD/blob/master/inst/scripts/generate-table-ad.R. There's a docker image for that repository, and there's a cron job in a service catalog EC2 that's supposed to pull the docker image weekly and run the script to update the table, but the cron job hasn't worked since August for no good reason that I can find so I just run it manually when we get new specimens.

**Comment by danlu1** [comment] 2022-01-21 00:25
Just want to share the discrepancies in config file btw apps here for your information. Haven't done checking on them yet in code, but I guess it will reveal some causes for the sync up issue. @afwillia 
<img width="960" alt="Screen Shot 2022-01-20 at 4 22 24 PM" src="https://user-images.githubusercontent.com/90745557/150443160-2418194a-d0f6-4053-a293-dfb8e23e6642.png">

<img width="378" alt="Screen Shot 2022-01-20 at 4 22 31 PM" src="https://user-images.githubusercontent.com/90745557/150443136-02cb332d-081b-406d-b203-cd5793e21180.png">

**Comment by afwillia** [comment] 2022-01-21 00:44
> @afwillia the code that generates/updates the Specimen Table is here: https://github.com/Sage-Bionetworks/cleanAD/blob/master/inst/scripts/generate-table-ad.R. There's a docker image for that repository, and there's a cron job in a service catalog EC2 that's supposed to pull the docker image weekly and run the script to update the table, but the cron job hasn't worked since August for no good reason that I can find so I just run it manually when we get new specimens.

Thanks @avanlinden you read my mind on how to update the specimen table. It seems to me that there are two different issues that might be worth splitting up.

The first is the dccvalidator/dccmonitor sync that our collaborator discovered, which is this current one. I think I've finally nailed the scope and issues for that mismatch and can possibly push a fix next week.

The second issue is keeping the specimen collection table up to date. I have no idea what this entails yet, but will read up on it. I'm also not sure if it's the source of those other dccvalidator errors in the original issue.

Possible third issue are the bugs and discrepancies you encountered trying to reproduce the APOEPSC study last week. If so, maybe fixing 1 and 2 will resolve this. Maybe not.

So moving forward I propose closing this issue once I push a fix for the original sync issue. Then opening another issue for this specimen table sync problem, which will inform a possible third issue.

How does all that sound to you? A lot of this is just to make sure I've understood all that's happening. I think this all ties into #https://github.com/Sage-Bionetworks/dccvalidator/issues/524 @avanlinden @danlu1 @ychae

**Comment by danlu1** [comment] 2022-01-21 00:48
@afwillia AD doesn't have **sample_table** in dccvaliator config file. It should be samples_table: "syn21578908" as dccmonitor.

**Comment by afwillia** [comment] 2022-01-21 01:17
> @afwillia AD doesn't have **sample_table** in dccvaliator config file. It should be samples_table: "syn21578908" as dccmonitor.

Interesting, it looks like the dccvalidator was using this same sample_table from the default config, even though amp-ad was specified in app.R.

**Comment by avanlinden** [comment] 2022-01-21 19:35
@afwillia Your approach outlined above sounds good! Thank you for your help here.

**Closed** 2022-01-26 20:43 UTC
